version: '3.8'

services:
  ubuntu-ssh:
    image: jefriherditriyanto/vps-ubuntu-server:1.0.15
    # https://gvisor.dev/docs/user_guide/install/
    runtime: runsc
    privileged: true
    # dns:
    #   - 8.8.8.8
    #   - 1.1.1.1
    # sysctls:
    #   - net.ipv4.ping_group_range=0 2147483647
    # ports:
    #   - "2222:22"
    #   - "6080:6080"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    storage_opt:
      size: '60G'
