version: '3.8'

services:
  ubuntu-ssh:
    image: jefriherditriyanto/vps-ubuntu-server:1.0.23
    # https://gvisor.dev/docs/user_guide/install/
    runtime: runsc
    privileged: true
    # ports:
    #   - "2222:22"
    #   - "6080:6080"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    storage_opt:
      size: '60G'
